# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.23.2-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.23.2-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sickguy/Documents/Projects/SickPool/server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sickguy/Documents/Projects/SickPool/server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@echo "Run CPack packaging tool..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@echo "Run CPack packaging tool for source..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cpack --config ./CPackSourceConfig.cmake /home/sickguy/Documents/Projects/SickPool/server/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@echo "Running CMake cache editor..."
	/opt/cmake-3.23.2-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@echo "Available install components are: \"Unspecified\" \"simdjson_Development\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@echo "Install the project..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@echo "Install the project..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@echo "Installing only the local directory..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@echo "Installing only the local directory..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@echo "Installing the project stripped..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@echo "Installing the project stripped..."
	/opt/cmake-3.23.2-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sickguy/Documents/Projects/SickPool/server/CMakeFiles /home/sickguy/Documents/Projects/SickPool/server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sickguy/Documents/Projects/SickPool/server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SickPool

# Build rule for target.
SickPool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SickPool
.PHONY : SickPool

# fast build rule for target.
SickPool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SickPool.dir/build.make CMakeFiles/SickPool.dir/build
.PHONY : SickPool/fast

#=============================================================================
# Target rules for targets named SickPool_core

# Build rule for target.
SickPool_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SickPool_core
.PHONY : SickPool_core

# fast build rule for target.
SickPool_core/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/SickPool_core.dir/build.make src/CMakeFiles/SickPool_core.dir/build
.PHONY : SickPool_core/fast

#=============================================================================
# Target rules for targets named simdjson

# Build rule for target.
simdjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simdjson
.PHONY : simdjson

# fast build rule for target.
simdjson/fast:
	$(MAKE) $(MAKESILENT) -f _deps/simdjson-build/CMakeFiles/simdjson.dir/build.make _deps/simdjson-build/CMakeFiles/simdjson.dir/build
.PHONY : simdjson/fast

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/fmt-build/CMakeFiles/fmt.dir/build.make _deps/fmt-build/CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named hiredis

# Build rule for target.
hiredis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hiredis
.PHONY : hiredis

# fast build rule for target.
hiredis/fast:
	$(MAKE) $(MAKESILENT) -f _deps/hiredis-build/CMakeFiles/hiredis.dir/build.make _deps/hiredis-build/CMakeFiles/hiredis.dir/build
.PHONY : hiredis/fast

#=============================================================================
# Target rules for targets named hiredis_static

# Build rule for target.
hiredis_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hiredis_static
.PHONY : hiredis_static

# fast build rule for target.
hiredis_static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/hiredis-build/CMakeFiles/hiredis_static.dir/build.make _deps/hiredis-build/CMakeFiles/hiredis_static.dir/build
.PHONY : hiredis_static/fast

#=============================================================================
# Target rules for targets named hiredis-test

# Build rule for target.
hiredis-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hiredis-test
.PHONY : hiredis-test

# fast build rule for target.
hiredis-test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/hiredis-build/CMakeFiles/hiredis-test.dir/build.make _deps/hiredis-build/CMakeFiles/hiredis-test.dir/build
.PHONY : hiredis-test/fast

#=============================================================================
# Target rules for targets named cryptonote_utils

# Build rule for target.
cryptonote_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cryptonote_utils
.PHONY : cryptonote_utils

# fast build rule for target.
cryptonote_utils/fast:
	$(MAKE) $(MAKESILENT) -f src/crypto/cn/CMakeFiles/cryptonote_utils.dir/build.make src/crypto/cn/CMakeFiles/cryptonote_utils.dir/build
.PHONY : cryptonote_utils/fast

#=============================================================================
# Target rules for targets named sickverushash

# Build rule for target.
sickverushash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sickverushash
.PHONY : sickverushash

# fast build rule for target.
sickverushash/fast:
	$(MAKE) $(MAKESILENT) -f src/crypto/verushash/CMakeFiles/sickverushash.dir/build.make src/crypto/verushash/CMakeFiles/sickverushash.dir/build
.PHONY : sickverushash/fast

#=============================================================================
# Target rules for targets named block_watcher

# Build rule for target.
block_watcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 block_watcher
.PHONY : block_watcher

# fast build rule for target.
block_watcher/fast:
	$(MAKE) $(MAKESILENT) -f src/blocks/CMakeFiles/block_watcher.dir/build.make src/blocks/CMakeFiles/block_watcher.dir/build
.PHONY : block_watcher/fast

#=============================================================================
# Target rules for targets named payout_manager

# Build rule for target.
payout_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 payout_manager
.PHONY : payout_manager

# fast build rule for target.
payout_manager/fast:
	$(MAKE) $(MAKESILENT) -f src/payouts/CMakeFiles/payout_manager.dir/build.make src/payouts/CMakeFiles/payout_manager.dir/build
.PHONY : payout_manager/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SickPool.dir/build.make CMakeFiles/SickPool.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SickPool.dir/build.make CMakeFiles/SickPool.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SickPool.dir/build.make CMakeFiles/SickPool.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... SickPool"
	@echo "... SickPool_core"
	@echo "... block_watcher"
	@echo "... cryptonote_utils"
	@echo "... fmt"
	@echo "... hiredis"
	@echo "... hiredis-test"
	@echo "... hiredis_static"
	@echo "... payout_manager"
	@echo "... sickverushash"
	@echo "... simdjson"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

